################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

include:
  - local: 'ci/defaults-php.yaml'

################################################################
# Defined Pipeline Stages
stages:
  - quality
  - functional
  - tests
  - deploy

################################################################
# Quality Tests
################################################################

quality:php-8.2:
    <<: *quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2

quality:php-8.1:
    <<: *quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0

#################################################################
## Base Job
#################################################################
#
#.base:    &base
#    tags:
#        - Dedicated
#    before_script:
#        ################################################################################
#        # Install Symfony
#        - composer update
#    after_script:
#        ################################################################################
#        # Run After Script
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh
#
#
#################################################################
## Functional Tests
#################################################################
#
#.core_tests:    &core_tests
#    stage:      tests
#    tags:
#        - Dedicated
#    services:
#        - mysql:5.7
#    artifacts:
#            when: always
#            reports:
#                junit: "$CI_PROJECT_DIR/*-report.xml"
#    ################################################################################
#    # Install & Configure Environment
#    before_script:
#        # Setup SendInBlue Connector
#        - sed -i -e 's/ThisIsSecretApiKey/'$MC_API_KEY'/g' tests/config/splash.yml >/dev/null 2>&1
#        - sed -i -e 's/ThisIsSecretApiList/'$MC_API_LIST'/g' tests/config/splash.yml >/dev/null 2>&1
#        # Setup Travis
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/configure.sh  | sh
#        # Deploy Symfony Files
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
#        # Setup Symfony Version & Create Database
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/configure.sh | sh
#        # Install Symfony
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/install.sh | sh
#
#    ################################################################################
#    # Run Test Script
#    script:
#        # Execute Grumphp Testsuite
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh  | sh
#        # Execute PhpUnit Tests
#        - vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/full-report.xml
#
#    ################################################################################
#    # Run After Script
#    after_script:
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh
#
#################################################################################
## PHP 8.1
#tests:php-8.1:
#  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
#  needs: ["tests:php-8.0"]
#  <<: *core_tests
#
#################################################################################
## PHP 8.0
#tests:php-8.0:
#    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
#    <<: *core_tests
#
#################################################################
## Build Documentation
#################################################################
#pages:
#    image:      jekyll/minimal:latest
#    stage:      deploy
#    tags:       [ Dedicated ]
#    ################################################################################
#    # Run Test Script
#    script:
#        - wget -qO - https://gitlab.com/badpixxel-robo/jekyll/-/raw/main/scripts/gitlab-pages.sh | sh
#    artifacts:
#        paths:
#            - public

