################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

include:
  - local: 'ci/defaults-php.yaml'
  - local: 'ci/pages.yaml'

################################################################
# Defined Pipeline Stages
stages:
  - quality
  - functional
  - deploy

################################################################
# Quality Tests
################################################################

quality:php-8.2:
  when: always

quality:php-8.1:
  when: always

quality:php-8.0:
  when: manual

quality:php-7.4:
  when: manual

################################################################
# Functional Tests
################################################################

functional:php-8.2:
    when: always

functional:php-8.1:
    when: always

functional:php-8.0:
    when: manual

functional:php-7.4:
    when: manual
