################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash SendInBlue Connector
#
# For a faster access to you container, you can add this IP to /etc/hosts
# 
# 172.110.0.100       toolkit.mailchimp.local
#
################################################################################

services:
    
    ################################################################################
    # Splash Toolkit Container   
    toolkit:
        image:              'splashsync/toolkit:2.5'
        container_name:     mailchimp-toolkit
        volumes:
            # Specify Local Configuration File
            - './config/packages/splash.yaml:/app/config/packages/splash.yaml:ro'
            # Uncomment to use Local Sources instead of Release
            - './src/:/app/vendor/splash/mailchimp/src/:ro'
        hostname:           toolkit.mailchimp.local
        networks:
            sendinblue:     { ipv4_address: 172.110.0.100, aliases: [ toolkit.mailchimp.local ] }
            splashsync:     { aliases: [ toolkit.mailchimp.local ] }

    ################################################################################
    # PHP 8.3
    php-8.3:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
        container_name: mailchimp-php-8.3
        volumes:
            - ./:/var/www/html
            - vendor-php83:/var/www/html/vendor

    ################################################################################
    # PHP 8.1
    php-8.1:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        container_name: mailchimp-php-8.1
        volumes:
            - ./:/var/www/html
            - vendor-php81:/var/www/html/vendor

networks:
    ################################################################################
    # Default Private Network    
    sendinblue:
        driver: bridge
        ipam:
            config:
                - subnet: 172.110.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true

volumes:
    vendor-php83: ~
    vendor-php81: ~
