services:
    ################################################################################
    # SPLASH MailChimp Connector Service
    splash.connectors.mailchimp:
        class: Splash\Connectors\MailChimp\Services\MailChimpConnector
        arguments:  [ "@event_dispatcher", "@logger" ]
        tags:       
            - { name: "splash.connector"}

    ################################################################################
    # Enables Dependency Injection in Controller Actions
    Splash\Connectors\MailChimp\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']