services:

    _defaults:
        autowire:           true
        autoconfigure:      true

    ################################################################################
    # Autowire for MailChimp Connector
    Splash\Connectors\MailChimp\Connectors\:
        resource: '../../Connectors'

    ################################################################################
    # Enables Dependency Injection in Actions
    Splash\Connectors\MailChimp\Actions\:
        resource: '../../Actions'
        public: true
        tags: ['controller.service_arguments']

    ################################################################################
    # Autowire for MailChimp Services
    Splash\Connectors\MailChimp\Services\:
        resource: '../../Services'
