
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Available Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # MailChimp Default
        mailchimp:
            id:                 ThisIsMailChimpWsId
            key:                ThisIsNotASecretKeyForMailChimp
            name:               Serveur 1 (MailChimp)
            connector:          mailchimp
            config:
                WsHost:         http://localhost:8000
                ApiKey:         ThisIsSecretApiKey
                ApiList:        ThisIsSecretApiList
